# Source: customer-waiting-room-app/templates/ktriggers.yaml
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: ui-tickets-payment-authorized-trigger
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  broker: default
  filter:
    attributes:
      type: Tickets.PaymentsAuthorized
  subscriber:
    uri: http://customer-waiting-room-app.default.svc.cluster.local/api/
