# Source: payments-service/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2020-10-21T09:22:54Z"
  deletionTimestamp: null
  name: 'payments-service-0.0.19'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: salaboy
      branch: master
      committer:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: salaboy
      message: |
        release 0.0.19
      sha: 05f1615e4363496e92ffb879958ee9728f2d81cf
    - author:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: salaboy@gmail.com
        name: salaboy
      branch: master
      committer:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: salaboy@gmail.com
        name: salaboy
      message: |
        Jenkins X build pack
      sha: df8b80d74a4f55e9d55249aa2e79226ab0c41d06
  gitCloneUrl: https://github.com/salaboy/payments-service.git
  gitHttpUrl: https://github.com/salaboy/payments-service
  gitOwner: salaboy
  gitRepository: payments-service
  name: 'payments-service'
  releaseNotesURL: https://github.com/salaboy/payments-service/releases/tag/v0.0.19
  version: v0.0.19
status: {}
