# Source: zeebe-operator/charts/tekton/templates/build-bot-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-bot
  namespace: jx-production
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
