# Source: jxboot-helmfile-resources/templates/npm-token-secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: jenkins-npm-token
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  backendType: gcpSecretsManager
  projectId: camunda-researchanddevelopment
  data:
    - name: token
      key: tf-jx-saved-worm-jenkins-npm-token
      version: latest
  template:
    type: Opaque
