# Source: fmtok8s-speakers/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2020-11-02T14:55:46Z"
  deletionTimestamp: null
  name: 'fmtok8s-speakers-0.0.7'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: salaboy
      branch: master
      committer:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: salaboy
      message: |
        release 0.0.7
      sha: 5f0d82437a7cfa8a7f8d6fb5b48f80d459f5637e
    - author:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: salaboy@gmail.com
        name: salaboy
      branch: master
      committer:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: salaboy@gmail.com
        name: salaboy
      message: |
        update deployment and ksvc
      sha: 1a9319528649aecbc00a2657bafb7075ddfe67f1
  gitCloneUrl: https://github.com/salaboy/fmtok8s-speakers.git
  gitHttpUrl: https://github.com/salaboy/fmtok8s-speakers
  gitOwner: salaboy
  gitRepository: fmtok8s-speakers
  name: 'fmtok8s-speakers'
  releaseNotesURL: https://github.com/salaboy/fmtok8s-speakers/releases/tag/v0.0.7
  version: v0.0.7
status: {}
