# Source: fmtok8s-speakers/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2020-10-21T11:29:45Z"
  deletionTimestamp: null
  name: 'fmtok8s-speakers-0.0.4'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: salaboy
      branch: master
      committer:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: salaboy
      message: |
        release 0.0.4
      sha: f6a8cfc432fbba5ed503bdb35163f800183da43f
    - author:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: salaboy@gmail.com
        name: salaboy
      branch: master
      committer:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: salaboy@gmail.com
        name: salaboy
      message: |
        Jenkins X build pack
      sha: 9d336f488dae34495d101e79c8f06aac637eff68
    - author:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: salaboy@gmail.com
        name: salaboy
      branch: master
      committer:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: salaboy@gmail.com
        name: salaboy
      message: |
        removing jx2
      sha: 0a6c5fc28079d6b4936b563fdfe07bebf5ca9dcb
  gitCloneUrl: https://github.com/salaboy/fmtok8s-speakers.git
  gitHttpUrl: https://github.com/salaboy/fmtok8s-speakers
  gitOwner: salaboy
  gitRepository: fmtok8s-speakers
  name: 'fmtok8s-speakers'
  releaseNotesURL: https://github.com/salaboy/fmtok8s-speakers/releases/tag/v0.0.4
  version: v0.0.4
status: {}
