# Source: fmtok8s-speakers/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2020-10-22T09:11:08Z"
  deletionTimestamp: null
  name: 'fmtok8s-speakers-0.0.6'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: salaboy
      branch: master
      committer:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: salaboy
      message: |
        release 0.0.6
      sha: abe22ae2432dbeeb7b18256a5a5a7e6743a6fdcd
    - author:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: salaboy@gmail.com
        name: salaboy
      branch: master
      committer:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: salaboy@gmail.com
        name: salaboy
      message: |
        adding external secret and increasing requests and limits
      sha: b456a4b184e24c1da4fa24d6ef65d65fdc7b9a88
  gitCloneUrl: https://github.com/salaboy/fmtok8s-speakers.git
  gitHttpUrl: https://github.com/salaboy/fmtok8s-speakers
  gitOwner: salaboy
  gitRepository: fmtok8s-speakers
  name: 'fmtok8s-speakers'
  releaseNotesURL: https://github.com/salaboy/fmtok8s-speakers/releases/tag/v0.0.6
  version: v0.0.6
status: {}
