filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
    - versionStream/src/fake-secrets.yaml.gotmpl
repositories:
- name: doesnotexist
  url: https://storage.googleapis.com/chartmuseum.jenkins-x.io
- name: cdf
  url: https://cdfoundation.github.io/tekton-helm-chart
- name: jenkins-x
  url: https://storage.googleapis.com/chartmuseum.jenkins-x.io
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: external-secrets
  url: https://godaddy.github.io/kubernetes-external-secrets
- name: jx-labs
  url: https://storage.googleapis.com/jenkinsxio-labs-private/charts
- name: jx3
  url: https://storage.googleapis.com/jenkinsxio/charts
- name: stable
  url: https://charts.helm.sh/stable
- name: dev
  url: http://chartmuseum-jx.35.222.17.41.nip.io/
releases:
- chart: jenkins-x/jxboot-helmfile-resources
  version: 1.0.12
  name: jxboot-helmfile-resources
  namespace: jx
  values:
  - versionStream/charts/jenkins-x/jxboot-helmfile-resources/values.yaml.gotmpl
- chart: external-secrets/kubernetes-external-secrets
  version: 5.2.0
  name: kubernetes-external-secrets
  namespace: secret-infra
  values:
  - versionStream/charts/external-secrets/kubernetes-external-secrets/values.yaml.gotmpl
- chart: jx-labs/jenkins-x-crds
  version: 0.0.7
  name: jenkins-x-crds
  namespace: jx
  values:
  - versionStream/charts/jx-labs/jenkins-x-crds/values.yaml
- chart: jx3/jx-pipelines-visualizer
  version: 0.0.51
  name: jx-pipelines-visualizer
  namespace: jx
  values:
  - versionStream/charts/jx3/jx-pipelines-visualizer/values.yaml.gotmpl
- chart: jx3/jx-preview
  version: 0.0.114
  name: jx-preview
  namespace: jx
- chart: stable/nginx-ingress
  version: 1.39.1
  name: nginx-ingress
  namespace: nginx
  values:
  - versionStream/charts/stable/nginx-ingress/values.yaml.gotmpl
- chart: cdf/tekton-pipeline
  version: 0.17.1
  name: tekton-pipeline
  namespace: tekton-pipelines
  values:
  - versionStream/charts/cdf/tekton-pipeline/values.yaml.gotmpl
- chart: jenkins-x/lighthouse
  version: 0.0.866
  name: lighthouse
  namespace: jx
  values:
  - versionStream/charts/jenkins-x/lighthouse/values.yaml.gotmpl
- chart: jenkins-x/nexus
  version: 0.1.35
  name: nexus
  namespace: jx
  values:
  - versionStream/charts/jenkins-x/nexus/values.yaml.gotmpl
  - persistence:
      size: 30Gi
- chart: jenkins-x/chartmuseum
  version: 1.1.7
  name: chartmuseum
  namespace: jx
  values:
  - versionStream/charts/jenkins-x/chartmuseum/values.yaml.gotmpl
- chart: jx-labs/pusher-wave
  version: 1.0.0
  name: pusher-wave
  namespace: secret-infra
- chart: jx3/jx-build-controller
  version: 0.0.14
  name: jx-build-controller
  namespace: jx
  values:
  - versionStream/charts/jx3/jx-build-controller/values.yaml.gotmpl
- chart: dev/fmtok8s-c4p-rest
  version: 0.0.9
  name: fmtok8s-c4p-rest
  namespace: jx-staging
- chart: dev/fmtok8s-agenda-rest
  version: 0.0.3
  name: fmtok8s-agenda-rest
  namespace: jx-staging
- chart: dev/fmtok8s-email-rest
  version: 0.0.3
  name: fmtok8s-email-rest
  namespace: jx-staging
- chart: dev/fmtok8s-api-gateway
  version: 0.0.125
  name: fmtok8s-api-gateway
  namespace: jx-staging
templates: {}
missingFileHandler: ""
