apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: tf-jx-saved-worm
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    gke:
      projectNumber: "291005901394"
    project: camunda-researchanddevelopment
    provider: gke
    registry: gcr.io
    zone: us-central1-a
  environments:
  - ingress:
      domain: "104.154.179.98.nip.io"
      externalDNS: false
      namespaceSubDomain: ""
      tls:
        email: ""
        enabled: false
        production: false
    key: dev
    owner: salaboy
    repository: jx3-cluster
  - ingress:
      domain: "104.154.179.98.nip.io"
      externalDNS: false
      namespaceSubDomain: ""
      tls:
        email: ""
        enabled: false
        production: false
    key: staging
  - ingress:
      domain: "104.154.179.98.nip.io"
      externalDNS: false
      namespaceSubDomain: ""
      tls:
        email: ""
        enabled: false
        production: false
    key: production
  ingress:
    domain: ""
    externalDNS: false
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: true
  pipelineUser:
    username: salaboy
  repository: nexus
  secretStorage: gsm
  storage:
  - name: logs
    url: gs://logs-tf-jx-saved-worm-0e4cf2b8dca6
  - name: reports
    url: gs://reports-tf-jx-saved-worm-0e4cf2b8dca6
  - name: repository
    url: gs://repository-tf-jx-saved-worm-0e4cf2b8dca6
  vault: {}
  webhook: lighthouse

