# Source: fmtok8s-agenda/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2020-11-03T13:26:52Z"
  deletionTimestamp: null
  name: 'fmtok8s-agenda-0.0.58'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: salaboy
      branch: master
      committer:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: salaboy
      message: |
        release 0.0.58
      sha: c049cf1692605fef538eb9227e1ed419d26590cf
    - author:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: salaboy@gmail.com
        name: salaboy
      branch: master
      committer:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: salaboy@gmail.com
        name: salaboy
      message: |
        check yaml indentation
      sha: 4c7b7a88be71d9bf8ab7ee20d25e80394b01ac10
  gitCloneUrl: https://github.com/salaboy/fmtok8s-agenda.git
  gitHttpUrl: https://github.com/salaboy/fmtok8s-agenda
  gitOwner: salaboy
  gitRepository: fmtok8s-agenda
  name: 'fmtok8s-agenda'
  releaseNotesURL: https://github.com/salaboy/fmtok8s-agenda/releases/tag/v0.0.58
  version: v0.0.58
status: {}
