# Source: fmtok8s-agenda/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2020-11-03T13:04:48Z"
  deletionTimestamp: null
  name: 'fmtok8s-agenda-0.0.57'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: salaboy
      branch: master
      committer:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: salaboy
      message: |
        release 0.0.57
      sha: bbb40331c7d5fc448830ea6ffb636c61659994d1
    - author:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: salaboy@gmail.com
        name: salaboy
      branch: master
      committer:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: salaboy@gmail.com
        name: salaboy
      message: |
        remove space typo
      sha: 0aa9614877cb2ffc1908fdfb9d776eda89ab5a09
  gitCloneUrl: https://github.com/salaboy/fmtok8s-agenda.git
  gitHttpUrl: https://github.com/salaboy/fmtok8s-agenda
  gitOwner: salaboy
  gitRepository: fmtok8s-agenda
  name: 'fmtok8s-agenda'
  releaseNotesURL: https://github.com/salaboy/fmtok8s-agenda/releases/tag/v0.0.57
  version: v0.0.57
status: {}
