# Source: fmtok8s-agenda/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2020-11-05T11:32:37Z"
  deletionTimestamp: null
  name: 'fmtok8s-agenda-0.0.65'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: salaboy
      branch: master
      committer:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: salaboy
      message: |
        release 0.0.65
      sha: ff0edf08efd4243e42f7a3b6475f88c1b6246093
    - author:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: salaboy@gmail.com
        name: salaboy
      branch: master
      committer:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: salaboy@gmail.com
        name: salaboy
      message: |
        adding events at the right level
      sha: 2ec79805ea4bb0d93ebc2995f4fb6592186be3cc
  gitCloneUrl: https://github.com/salaboy/fmtok8s-agenda.git
  gitHttpUrl: https://github.com/salaboy/fmtok8s-agenda
  gitOwner: salaboy
  gitRepository: fmtok8s-agenda
  name: 'fmtok8s-agenda'
  releaseNotesURL: https://github.com/salaboy/fmtok8s-agenda/releases/tag/v0.0.65
  version: v0.0.65
status: {}
