# Source: tickets-service/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2020-10-23T09:26:26Z"
  deletionTimestamp: null
  name: 'tickets-service-0.0.43'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: salaboy
      branch: master
      committer:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: salaboy
      message: |
        release 0.0.43
      sha: 942772cdd0c9df2ca951a3ec350203dc3b92e555
    - author:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: salaboy@gmail.com
        name: salaboy
      branch: master
      committer:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: salaboy@gmail.com
        name: salaboy
      message: |
        using correct port
      sha: f4ee1cedb87039da5a4ad58274845c11bff779c3
  gitCloneUrl: https://github.com/salaboy/tickets-service.git
  gitHttpUrl: https://github.com/salaboy/tickets-service
  gitOwner: salaboy
  gitRepository: tickets-service
  name: 'tickets-service'
  releaseNotesURL: https://github.com/salaboy/tickets-service/releases/tag/v0.0.43
  version: v0.0.43
status: {}
