# Source: tickets-service/templates/ktriggers.yaml
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: tickets-tickets-payment-requested-trigger
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  broker: default
  filter:
    attributes:
      type: Tickets.PaymentRequested
  subscriber:
    uri: http://tickets-service.default.svc.cluster.local/checkout
