# Source: fmtok8s-c4p-rest/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-01-25T08:54:07Z"
  deletionTimestamp: null
  name: 'fmtok8s-c4p-rest-0.0.16'
  namespace: jx-production
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: release 0.0.16
      sha: bc8e46c5588e54e73814e8d230f2b65567b470ef
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: add variables
      sha: f4197b40da12fabec5d5780e4e993eb735e32088
    - author:
        email: salaboy@gmail.com
        name: salaboy
      branch: master
      committer:
        email: salaboy@gmail.com
        name: salaboy
      message: |
        injecting span filter to webclient
      sha: 45bf9f862c30852b15031b3d31912bc4f3190756
  gitHttpUrl: https://github.com/salaboy/fmtok8s-c4p-rest
  gitOwner: salaboy
  gitRepository: fmtok8s-c4p-rest
  name: 'fmtok8s-c4p-rest'
  releaseNotesURL: https://github.com/salaboy/fmtok8s-c4p-rest/releases/tag/v0.0.16
  version: v0.0.16
status: {}
