# Source: fmtok8s-agenda-rest/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-01-23T10:48:53Z"
  deletionTimestamp: null
  name: 'fmtok8s-agenda-rest-0.0.9'
  namespace: jx-production
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: release 0.0.9
      sha: b9b0a7a69e1bcbfce07da7efea10d8a996fdf8e8
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: add variables
      sha: 90dba683ab0cde7fe52f74bba5b2bd8b4985c506
    - author:
        email: salaboy@gmail.com
        name: salaboy
      branch: master
      committer:
        email: salaboy@gmail.com
        name: salaboy
      message: |
        adding jaeger and spring boot name
      sha: 359956a3bfc3582dfdcbd5c150d69db598938741
  gitHttpUrl: https://github.com/salaboy/fmtok8s-agenda-rest
  gitOwner: salaboy
  gitRepository: fmtok8s-agenda-rest
  name: 'fmtok8s-agenda-rest'
  releaseNotesURL: https://github.com/salaboy/fmtok8s-agenda-rest/releases/tag/v0.0.9
  version: v0.0.9
status: {}
