# Source: fmtok8s-monolith/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2020-10-13T11:28:48Z"
  deletionTimestamp: null
  name: 'fmtok8s-monolith-0.0.21'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        accountReference:
          - provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: salaboy
      branch: master
      committer:
        accountReference:
          - id: salaboy-0
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: salaboy
      message: |
        release 0.0.21
      sha: b0fab1e9bcd003aa3a1d1c040ab443ea3158d8e3
    - author:
        accountReference:
          - provider: jenkins.io/git-github-userid
        email: salaboy@gmail.com
        name: salaboy
      branch: master
      committer:
        accountReference:
          - id: salaboy-1
            provider: jenkins.io/git-github-userid
        email: salaboy@gmail.com
        name: salaboy
      message: |
        Jenkins X build pack
      sha: 0ff8a35e6bd111e948df0471162c98ffed0cfeef
    - author:
        accountReference:
          - id: salaboy-1
            provider: jenkins.io/git-github-userid
        email: salaboy@gmail.com
        name: salaboy
      branch: master
      committer:
        accountReference:
          - id: salaboy-1
            provider: jenkins.io/git-github-userid
        email: salaboy@gmail.com
        name: salaboy
      message: |
        removing jx
      sha: a0325a68d1720112f822d51b7fa75be641e1281c
    - author:
        accountReference:
          - id: salaboy-1
            provider: jenkins.io/git-github-userid
        email: salaboy@gmail.com
        name: salaboy
      branch: master
      committer:
        accountReference:
          - id: salaboy-1
            provider: jenkins.io/git-github-userid
        email: salaboy@gmail.com
        name: salaboy
      message: |
        adding jx files
      sha: 38fd0c5cb0d76527caaa22184622b35274f0dc0e
    - author:
        accountReference:
          - id: salaboy-1
            provider: jenkins.io/git-github-userid
        email: salaboy@gmail.com
        name: salaboy
      branch: master
      committer:
        accountReference:
          - id: salaboy-1
            provider: jenkins.io/git-github-userid
        email: salaboy@gmail.com
        name: salaboy
      message: |
        remove jx
      sha: 6b597a1e6320da1c0b15c406e6526655d1ae09f4
    - author:
        accountReference:
          - id: salaboy-1
            provider: jenkins.io/git-github-userid
        email: salaboy@gmail.com
        name: salaboy
      branch: master
      committer:
        accountReference:
          - id: salaboy-1
            provider: jenkins.io/git-github-userid
        email: salaboy@gmail.com
        name: salaboy
      message: |
        Jenkins X build pack
      sha: bce4edd2024f7fbb67f843719914989190409130
    - author:
        accountReference:
          - id: salaboy-1
            provider: jenkins.io/git-github-userid
        email: salaboy@gmail.com
        name: salaboy
      branch: master
      committer:
        accountReference:
          - id: salaboy-1
            provider: jenkins.io/git-github-userid
        email: salaboy@gmail.com
        name: salaboy
      message: |
        removing lighthouse files
      sha: a994d1def6e9a5bd5d57e0f34e0e5d51f7a9560f
    - author:
        accountReference:
          - provider: jenkins.io/git-github-userid
        email: Salaboy@gmail.com
        name: salaboy
      branch: master
      committer:
        accountReference:
          - provider: jenkins.io/git-github-userid
        email: noreply@github.com
        name: GitHub
      message: Update README.md
      sha: a576aebf9eac7d7de32791c47b9b4e529dcbf3e7
    - author:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: Salaboy@gmail.com
        name: salaboy
      branch: master
      committer:
        accountReference:
          - id: github-0
            provider: jenkins.io/git-github-userid
        email: noreply@github.com
        name: GitHub
      message: Update README.md
      sha: f1cbecadfd0344ca8b702397ade034da41f5edcd
    - author:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: Salaboy@gmail.com
        name: salaboy
      branch: master
      committer:
        accountReference:
          - id: github-0
            provider: jenkins.io/git-github-userid
        email: noreply@github.com
        name: GitHub
      message: Update Dockerfile
      sha: 8fc6c5a9367d1410abbf90178cd29eb497dcee8e
    - author:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: Salaboy@gmail.com
        name: salaboy
      branch: master
      committer:
        accountReference:
          - id: github-0
            provider: jenkins.io/git-github-userid
        email: noreply@github.com
        name: GitHub
      message: Update pom.xml
      sha: 13a2b1a17826eb4221e3d49120fec524d78f992d
    - author:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: Salaboy@gmail.com
        name: salaboy
      branch: master
      committer:
        accountReference:
          - id: github-0
            provider: jenkins.io/git-github-userid
        email: noreply@github.com
        name: GitHub
      message: Update README.md
      sha: 0fc0cf6e115259abef0d7176d767e9d118bf7fc7
  gitCloneUrl: https://github.com/salaboy/fmtok8s-monolith.git
  gitHttpUrl: https://github.com/salaboy/fmtok8s-monolith
  gitOwner: salaboy
  gitRepository: fmtok8s-monolith
  name: 'fmtok8s-monolith'
  releaseNotesURL: https://github.com/salaboy/fmtok8s-monolith/releases/tag/v0.0.21
  version: v0.0.21
status: {}
