filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx-staging
repositories:
- name: dev2
  url: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
templates: {}
renderedvalues: {}
