# Source: jx-preview/templates/previews.preview.jenkins.io.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: previews.preview.jenkins.io
  labels:
    gitops.jenkins-x.io/pipeline: 'cluster'
spec:
  group: preview.jenkins.io
  names:
    kind: Preview
    singular: preview
    plural: previews
    shortNames:
      - pvw
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
