apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        salaboy/fmtok8s-agenda: true
        salaboy/fmtok8s-api-gateway: true
        salaboy/fmtok8s-app: true
        salaboy/fmtok8s-c4p: true
        salaboy/fmtok8s-email: true
        salaboy/fmtok8s-monolith: true
        salaboy/jx3-cluster: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: false
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        salaboy/fmtok8s-agenda: merge
        salaboy/fmtok8s-api-gateway: merge
        salaboy/fmtok8s-app: merge
        salaboy/fmtok8s-c4p: merge
        salaboy/fmtok8s-email: merge
        salaboy/fmtok8s-monolith: merge
        salaboy/jx3-cluster: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - salaboy/jx3-cluster
        - salaboy/fmtok8s-agenda
        - salaboy/fmtok8s-api-gateway
        - salaboy/fmtok8s-app
        - salaboy/fmtok8s-c4p
        - salaboy/fmtok8s-email
        - salaboy/fmtok8s-monolith
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - salaboy/jx3-cluster
        - salaboy/fmtok8s-agenda
        - salaboy/fmtok8s-api-gateway
        - salaboy/fmtok8s-app
        - salaboy/fmtok8s-c4p
        - salaboy/fmtok8s-email
        - salaboy/fmtok8s-monolith
      target_url: http://dashboard-jx.35.222.17.41.nip.io
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
