apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        salaboy/customer-waiting-room-app: true
        salaboy/fmtok8s-agenda: true
        salaboy/fmtok8s-agenda-rest: true
        salaboy/fmtok8s-api-gateway: true
        salaboy/fmtok8s-app: true
        salaboy/fmtok8s-app-v2: true
        salaboy/fmtok8s-app-v3: true
        salaboy/fmtok8s-c4p: true
        salaboy/fmtok8s-c4p-rest: true
        salaboy/fmtok8s-email: true
        salaboy/fmtok8s-email-rest: true
        salaboy/fmtok8s-monolith: true
        salaboy/fmtok8s-speakers: true
        salaboy/jx3-cluster: true
        salaboy/payments-service: true
        salaboy/queue-service: true
        salaboy/tickets-service: true
        zeebe-io/zeebe-cloud-events-router: true
        zeebe-io/zeebe-cluster-helm: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: false
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        salaboy/customer-waiting-room-app: merge
        salaboy/fmtok8s-agenda: merge
        salaboy/fmtok8s-agenda-rest: merge
        salaboy/fmtok8s-api-gateway: merge
        salaboy/fmtok8s-app: merge
        salaboy/fmtok8s-app-v2: merge
        salaboy/fmtok8s-app-v3: merge
        salaboy/fmtok8s-c4p: merge
        salaboy/fmtok8s-c4p-rest: merge
        salaboy/fmtok8s-email: merge
        salaboy/fmtok8s-email-rest: merge
        salaboy/fmtok8s-monolith: merge
        salaboy/fmtok8s-speakers: merge
        salaboy/jx3-cluster: merge
        salaboy/payments-service: merge
        salaboy/queue-service: merge
        salaboy/tickets-service: merge
        zeebe-io/zeebe-cloud-events-router: merge
        zeebe-io/zeebe-cluster-helm: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - salaboy/jx3-cluster
        - salaboy/customer-waiting-room-app
        - salaboy/fmtok8s-agenda-rest
        - salaboy/fmtok8s-agenda
        - salaboy/fmtok8s-api-gateway
        - salaboy/fmtok8s-app-v2
        - salaboy/fmtok8s-app-v3
        - salaboy/fmtok8s-app
        - salaboy/fmtok8s-c4p-rest
        - salaboy/fmtok8s-c4p
        - salaboy/fmtok8s-email-rest
        - salaboy/fmtok8s-email
        - salaboy/fmtok8s-monolith
        - salaboy/fmtok8s-speakers
        - salaboy/payments-service
        - salaboy/queue-service
        - salaboy/tickets-service
        - zeebe-io/zeebe-cloud-events-router
        - zeebe-io/zeebe-cluster-helm
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - salaboy/jx3-cluster
        - salaboy/customer-waiting-room-app
        - salaboy/fmtok8s-agenda-rest
        - salaboy/fmtok8s-agenda
        - salaboy/fmtok8s-api-gateway
        - salaboy/fmtok8s-app-v2
        - salaboy/fmtok8s-app-v3
        - salaboy/fmtok8s-app
        - salaboy/fmtok8s-c4p-rest
        - salaboy/fmtok8s-c4p
        - salaboy/fmtok8s-email-rest
        - salaboy/fmtok8s-email
        - salaboy/fmtok8s-monolith
        - salaboy/fmtok8s-speakers
        - salaboy/payments-service
        - salaboy/queue-service
        - salaboy/tickets-service
        - zeebe-io/zeebe-cloud-events-router
        - zeebe-io/zeebe-cluster-helm
      target_url: http://dashboard-jx.35.222.17.41.nip.io
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
