# Source: fmtok8s-api-gateway/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: fmtok8s-api-gateway
  labels:
    chart: "fmtok8s-api-gateway-0.0.119"
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: 'kubernetes.io/ingress.class: nginx'
  namespace: jx-staging
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: fmtok8s-api-gateway-fmtok8s-api-gateway
