# Source: fmtok8s-api-gateway/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2020-11-02T20:09:03Z"
  deletionTimestamp: null
  name: 'fmtok8s-api-gateway-0.0.119'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: salaboy
      branch: master
      committer:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: salaboy
      message: |
        release 0.0.119
      sha: ea7e7d281ca20ac90b991f646ee8b704fcc824e9
    - author:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: salaboy@gmail.com
        name: salaboy
      branch: master
      committer:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: salaboy@gmail.com
        name: salaboy
      message: |
        ignoring contract testing due 401 in nexus
      sha: 0cf8bdbb43a40b411a36307e7f391514df2ef3e4
  gitCloneUrl: https://github.com/salaboy/fmtok8s-api-gateway.git
  gitHttpUrl: https://github.com/salaboy/fmtok8s-api-gateway
  gitOwner: salaboy
  gitRepository: fmtok8s-api-gateway
  name: 'fmtok8s-api-gateway'
  releaseNotesURL: https://github.com/salaboy/fmtok8s-api-gateway/releases/tag/v0.0.119
  version: v0.0.119
status: {}
