# Source: zeebe-zeeqs-helm/charts/hazelcast/templates/mancenter-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zeebe-zeeqs-helm-hazelcast-mancenter
  labels:
    app.kubernetes.io/name: hazelcast-mancenter
    helm.sh/chart: hazelcast-3.5.0
    app.kubernetes.io/instance: "zeebe-zeeqs-helm"
    app.kubernetes.io/managed-by: "Helm"
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: jx-staging
spec:
  serviceName: zeebe-zeeqs-helm-hazelcast-mancenter
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hazelcast-mancenter
      app.kubernetes.io/instance: "zeebe-zeeqs-helm"
      role: mancenter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hazelcast-mancenter
        helm.sh/chart: hazelcast-3.5.0
        app.kubernetes.io/instance: "zeebe-zeeqs-helm"
        app.kubernetes.io/managed-by: "Helm"
        role: mancenter
    spec:
      hostNetwork: false
      hostPID: false
      hostIPC: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
      containers:
        - name: zeebe-zeeqs-helm-hazelcast-mancenter
          image: "hazelcast/management-center:4.2020.10"
          imagePullPolicy: "IfNotPresent"
          resources: null
          ports:
            - name: mancenter
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - name: config
              mountPath: /config
            - name: mancenter-storage
              mountPath: /data
          env:
            - name: MC_LICENSE_KEY
              value:
            - name: MC_INIT_CMD
              value: "./mc-conf.sh cluster add --lenient=true -H /data -cc /config/hazelcast-client.yaml"
            - name: JAVA_OPTS
              value: " -Dhazelcast.mc.healthCheck.enable=true -DserviceName=zeebe-zeeqs-helm-hazelcast -Dnamespace=jx-staging -Dhazelcast.mc.tls.enabled=false "
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      securityContext:
        fsGroup: 65534
      serviceAccountName: zeebe-zeeqs-helm-hazelcast
      automountServiceAccountToken: true
      volumes:
        - name: config
          configMap:
            name: zeebe-zeeqs-helm-hazelcast-mancenter-configuration
        - name: mancenter-storage
  volumeClaimTemplates:
    - metadata:
        name: mancenter-storage
        labels:
          app.kubernetes.io/name: hazelcast-mancenter
          helm.sh/chart: "hazelcast-3.5.0"
          app.kubernetes.io/instance: "zeebe-zeeqs-helm"
          app.kubernetes.io/managed-by: "Helm"
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "8Gi"
