# Source: zeebe-zeeqs-helm/charts/hazelcast/templates/config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: zeebe-zeeqs-helm-hazelcast-configuration
  labels:
    app.kubernetes.io/name: hazelcast
    helm.sh/chart: hazelcast-3.5.0
    app.kubernetes.io/instance: "zeebe-zeeqs-helm"
    app.kubernetes.io/managed-by: "Helm"
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: jx-staging
data:
  hazelcast.yaml: |-
    hazelcast:
      network:
        join:
          kubernetes:
            enabled: true
            namespace: ${namespace}
            service-name: ${serviceName}
          multicast:
            enabled: false
        rest-api:
          enabled: true
          endpoint-groups:
            HEALTH_CHECK:
              enabled: true
