# Source: fmtok8s-email/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2020-11-02T20:23:39Z"
  deletionTimestamp: null
  name: 'fmtok8s-email-0.0.46'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: salaboy
      branch: master
      committer:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: salaboy
      message: |
        release 0.0.46
      sha: a1027fec7675293b965b1edaa9c0c307cd482c39
    - author:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: salaboy@gmail.com
        name: salaboy
      branch: master
      committer:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: salaboy@gmail.com
        name: salaboy
      message: |
        updating condition external secrets
      sha: 2081c44b73d68c04d0fa5156a7cfc13c6a9f9cc9
  gitCloneUrl: https://github.com/salaboy/fmtok8s-email.git
  gitHttpUrl: https://github.com/salaboy/fmtok8s-email
  gitOwner: salaboy
  gitRepository: fmtok8s-email
  name: 'fmtok8s-email'
  releaseNotesURL: https://github.com/salaboy/fmtok8s-email/releases/tag/v0.0.46
  version: v0.0.46
status: {}
