# Source: zeebe-full-helm/charts/nginx-ingress/templates/default-backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-ingress
    chart: nginx-ingress-1.26.2
    component: "default-backend"
    heritage: Helm
    release: zeebe-full-helm
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: zeebe-full-helm-nginx-ingress-default-backend
  namespace: jx-staging
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: nginx-ingress
    component: "default-backend"
    release: zeebe-full-helm
  type: "ClusterIP"
