# Source: zeebe-full-helm/charts/nginx-ingress/templates/default-backend-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: nginx-ingress
    chart: nginx-ingress-1.26.2
    heritage: Helm
    release: zeebe-full-helm
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: zeebe-full-helm-nginx-ingress-backend
  namespace: jx-staging
