# Source: fmtok8s-email-rest/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-01-21T18:17:32Z"
  deletionTimestamp: null
  name: 'fmtok8s-email-rest-0.0.7'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: release 0.0.7
      sha: 8eb77c1c7c030dee54fbd306bd881a8d8a98b34d
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: add variables
      sha: c071d4c09227354d87807a6e319767993b1711d4
    - author:
        email: salaboy@gmail.com
        name: salaboy
      branch: master
      committer:
        email: salaboy@gmail.com
        name: salaboy
      message: |
        adding prometheus metrics collector
      sha: 36fdf13a8982b5ce3e079691ebc010140e09d09f
  gitHttpUrl: https://github.com/salaboy/fmtok8s-email-rest
  gitOwner: salaboy
  gitRepository: fmtok8s-email-rest
  name: 'fmtok8s-email-rest'
  releaseNotesURL: https://github.com/salaboy/fmtok8s-email-rest/releases/tag/v0.0.7
  version: v0.0.7
status: {}
