# Source: zeebe-zeeqs-helm/charts/hazelcast/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zeebe-zeeqs-helm-hazelcast-jx-staging
  labels:
    app.kubernetes.io/name: hazelcast
    helm.sh/chart: hazelcast-3.5.0
    app.kubernetes.io/instance: "zeebe-zeeqs-helm"
    app.kubernetes.io/managed-by: "Helm"
    gitops.jenkins-x.io/pipeline: 'cluster'
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
      - pods
      - nodes
    verbs:
      - get
      - list
