# Source: zeebe-operator/charts/tekton/templates/webhook.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tekton-pipelines-webhook
    role: webhook
    pipeline.tekton.dev/release: v0.11.3
    version: v0.11.3
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: tekton-pipelines-webhook
  namespace: jx-staging
spec:
  ports:
    # Define metrics and profiling for them to be accessible within service meshes.
    - name: http-metrics
      port: 9090
      targetPort: 9090
    - name: http-profiling
      port: 8008
      targetPort: 8008
    - name: https-webhook
      port: 443
      targetPort: 8443
  selector:
    app: tekton-pipelines-webhook
    role: webhook
