# Source: zeebe-zeeqs-helm/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2020-12-01T12:16:28Z"
  deletionTimestamp: null
  name: 'zeebe-zeeqs-helm-0.0.18'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: added variables
      sha: 1eb78508facae30902113707f7761648c1d780a0
    - author:
        email: salaboy@gmail.com
        name: salaboy
      branch: master
      committer:
        email: salaboy@gmail.com
        name: salaboy
      message: |
        hazelcast own repo
      sha: d63a429badf088a5a242198f4b1a48dabf09981e
  gitHttpUrl: https://github.com/zeebe-io/zeebe-zeeqs-helm
  gitOwner: zeebe-io
  gitRepository: zeebe-zeeqs-helm
  name: 'zeebe-zeeqs-helm'
  releaseNotesURL: https://github.com/zeebe-io/zeebe-zeeqs-helm/releases/tag/v0.0.18
  version: v0.0.18
status: {}
