# Source: zeebe-zeeqs-helm/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: zeebe-zeeqs-helm
  labels:
    app: zeebe-zeeqs-helm
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: jx-staging
spec:
  type: ClusterIP
  ports:
    - port: 9000
      name: http
      targetPort: 9000
      protocol: TCP
  selector:
    app: zeebe-zeeqs-helm
