# Source: cd-flow-backend/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-01-15T10:16:40Z"
  deletionTimestamp: null
  name: 'cd-flow-backend-0.0.4'
  namespace: jx-production
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: release 0.0.4
      sha: 4cd87047cb35fa096e0d79ed39b887e31ebcc373
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: add variables
      sha: acf561f7c18a492d2f9e1ec9ddc26d0c5c740e36
    - author:
        email: salaboy@gmail.com
        name: salaboy
      branch: master
      committer:
        email: salaboy@gmail.com
        name: salaboy
      message: |
        adding metrics
      sha: 721ce5e4d6b7fee043d924413afe41e4c2f02726
  gitHttpUrl: https://github.com/salaboy/cd-flow-backend
  gitOwner: salaboy
  gitRepository: cd-flow-backend
  name: 'cd-flow-backend'
  releaseNotesURL: https://github.com/salaboy/cd-flow-backend/releases/tag/v0.0.4
  version: v0.0.4
status: {}
