# Source: queue-service/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2020-10-24T09:56:53Z"
  deletionTimestamp: null
  name: 'queue-service-0.0.40'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: salaboy
      branch: master
      committer:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: salaboy
      message: |
        release 0.0.40
      sha: eb02c9041a3d52238a2b8cebb17899e7809e0262
    - author:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: salaboy@gmail.com
        name: salaboy
      branch: master
      committer:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: salaboy@gmail.com
        name: salaboy
      message: |
        adding server port as ENV Variable
      sha: 5b8aa920fed21e993c50808bc99809547745db98
  gitCloneUrl: https://github.com/salaboy/queue-service.git
  gitHttpUrl: https://github.com/salaboy/queue-service
  gitOwner: salaboy
  gitRepository: queue-service
  name: 'queue-service'
  releaseNotesURL: https://github.com/salaboy/queue-service/releases/tag/v0.0.40
  version: v0.0.40
status: {}
