# Source: queue-service/templates/ktrigger.yaml
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: queue-join-trigger
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  broker: default
  filter:
    attributes:
      type: Queue.CustomerJoined
  subscriber:
    uri: http://queue-service.default.svc.cluster.local/join/
