# Source: zeebe-full-helm/charts/zeebe-cluster-helm/templates/configmap.yaml
kind: ConfigMap
metadata:
  name: zeebe-full-helm-zeebe-cluster-helm
  labels:
    app.kubernetes.io/name: zeebe-cluster-helm
    app.kubernetes.io/instance: zeebe-full-helm
    app.kubernetes.io/managed-by: Helm
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: jx-staging
apiVersion: v1
data:
  startup.sh: "#!/usr/bin/env bash\nset -eux -o pipefail\n\nexport ZEEBE_BROKER_NETWORK_ADVERTISEDHOST=${ZEEBE_BROKER_NETWORK_ADVERTISEDHOST:-$(hostname -f)}\nexport ZEEBE_BROKER_CLUSTER_NODEID=${ZEEBE_BROKER_CLUSTER_NODEID:-${K8S_POD_NAME##*-}}\n\n# As the number of replicas or the DNS is not obtainable from the downward API yet,\n# defined them here based on conventions\nexport ZEEBE_BROKER_CLUSTER_CLUSTERSIZE=${ZEEBE_BROKER_CLUSTER_CLUSTERSIZE:-1}\ncontactPointPrefix=${K8S_POD_NAME%-*}\ncontactPoints=${ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS:-\"\"}\nif [[ -z \"${contactPoints}\" ]]; then\n  for ((i=0; i<${ZEEBE_BROKER_CLUSTER_CLUSTERSIZE}; i++))\n  do\n    contactPoints=\"${contactPoints},${contactPointPrefix}-$i.$(hostname -d):26502\"\n  done\n\n  export ZEEBE_BROKER_CLUSTER_INITIALCONTACTPOINTS=\"${contactPoints}\"\nfi\n\nif [ \"$(ls -A /exporters/)\" ]; then\n  mkdir /usr/local/zeebe/exporters/\n  cp -a /exporters/*.jar /usr/local/zeebe/exporters/\nelse  \n  echo \"No exporters available.\"\nfi\n\nexec /usr/local/zeebe/bin/broker\n"
  application.yaml: ""
  broker-log4j2.xml: ""
  gateway-log4j2.xml: ""
