# Source: zeebe-full-helm/charts/zeebe-cluster-helm/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2020-12-01T13:04:27Z"
  deletionTimestamp: null
  name: 'zeebe-cluster-helm-0.0.202'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        accountReference:
          - id: jenkins-x-bot
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: salaboy
      branch: master
      committer:
        accountReference:
          - id: jenkins-x-bot
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: salaboy
      message: |
        chore: added variables
      sha: 93fccdbbadf8e4533121ee065355cc4778e4931f
    - author:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: salaboy@gmail.com
        name: salaboy
      branch: master
      committer:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: salaboy@gmail.com
        name: salaboy
      message: |
        also checking for repository only at the beginning of a new line
      sha: c3de5f948c1710f866bbecf6ca7a6577f3abf6a9
  gitCloneUrl: https://github.com/zeebe-io/zeebe-cluster-helm.git
  gitHttpUrl: https://github.com/zeebe-io/zeebe-cluster-helm
  gitOwner: zeebe-io
  gitRepository: zeebe-cluster-helm
  name: 'zeebe-cluster-helm'
  releaseNotesURL: https://github.com/zeebe-io/zeebe-cluster-helm/releases/tag/v0.0.202
  version: v0.0.202
status: {}
