# Source: zeebe-full-helm/charts/zeebe-cluster-helm/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2020-12-01T15:11:03Z"
  deletionTimestamp: null
  name: 'zeebe-cluster-helm-0.0.204'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        accountReference:
          - id: jenkins-x-bot
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: salaboy
      branch: master
      committer:
        accountReference:
          - id: jenkins-x-bot
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: salaboy
      message: |
        chore: added variables
      sha: 779225bdc6e7af0e56c0fe04e809065f636bf4ba
    - author:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: salaboy@gmail.com
        name: salaboy
      branch: master
      committer:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: salaboy@gmail.com
        name: salaboy
      message: |
        removing repo name
      sha: 095c3299a082af262fb51792a0dcfc82b9b6c816
  gitCloneUrl: https://github.com/zeebe-io/zeebe-cluster-helm.git
  gitHttpUrl: https://github.com/zeebe-io/zeebe-cluster-helm
  gitOwner: zeebe-io
  gitRepository: zeebe-cluster-helm
  name: 'zeebe-cluster-helm'
  releaseNotesURL: https://github.com/zeebe-io/zeebe-cluster-helm/releases/tag/v0.0.204
  version: v0.0.204
status: {}
