# Source: zeebe-full-helm/charts/zeebe-cluster-helm/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: "zeebe-full-helm-zeebe"
  labels:
    app.kubernetes.io/name: zeebe-cluster-helm
    app.kubernetes.io/instance: zeebe-full-helm
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: broker
    app: zeebe
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations: null
  namespace: jx-staging
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  type: ClusterIP
  ports:
    - port: 9600
      protocol: TCP
      name: http
    - port: 26502
      protocol: TCP
      name: internal
    - port: 26501
      protocol: TCP
      name: command
  selector:
    app.kubernetes.io/name: zeebe-cluster-helm
    app.kubernetes.io/instance: zeebe-full-helm
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: broker
