# Source: zeebe-tasklist-helm/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2020-12-01T15:16:26Z"
  deletionTimestamp: null
  name: 'zeebe-tasklist-helm-0.0.9'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: added variables
      sha: b67a84f6da2b78d02b4ccf04a47499dd35d9e69d
    - author:
        email: salaboy@gmail.com
        name: salaboy
      branch: master
      committer:
        email: salaboy@gmail.com
        name: salaboy
      message: |
        adding jx crds dep
      sha: a11ab60e7cf47a129d507be1bfdc98c8c34fe6c1
  gitHttpUrl: https://github.com/zeebe-io/zeebe-tasklist-helm
  gitOwner: zeebe-io
  gitRepository: zeebe-tasklist-helm
  name: 'zeebe-tasklist-helm'
  releaseNotesURL: https://github.com/zeebe-io/zeebe-tasklist-helm/releases/tag/v0.0.9
  version: v0.0.9
status: {}
