# Source: zeebe-tasklist-helm/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2020-12-01T13:07:38Z"
  deletionTimestamp: null
  name: 'zeebe-tasklist-helm-0.0.8'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      branch: master
      committer:
        email: jenkins-x@googlegroups.com
        name: jenkins-x-bot
      message: |
        chore: added variables
      sha: b18e06dcf520f5895849d1c7486beba60cb29332
    - author:
        email: salaboy@gmail.com
        name: salaboy
      branch: master
      committer:
        email: salaboy@gmail.com
        name: salaboy
      message: |
        replacing repo and tag only at the beggining of a new line
      sha: 0202ae6bd1aac1271c61f1f84a11dc64c570672c
  gitHttpUrl: https://github.com/zeebe-io/zeebe-tasklist-helm
  gitOwner: zeebe-io
  gitRepository: zeebe-tasklist-helm
  name: 'zeebe-tasklist-helm'
  releaseNotesURL: https://github.com/zeebe-io/zeebe-tasklist-helm/releases/tag/v0.0.8
  version: v0.0.8
status: {}
