apiVersion: config.lighthouse.jenkins-x.io/v1alpha1
kind: TriggerConfig
spec:
  presubmits:
  - name: verify
    context: "verify"
    always_run: true
    optional: false
    trigger: "/test"
    rerun_command: "/retest"
    source: "pullrequest.yaml"
    queries:
    - excludedBranches: {}
      included_branches: {}
      labels:
        entries:
        - approved
      milestone: ""
      missingLabels:
        entries:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
      review_approved_required: false
    - excludedBranches: {}
      included_branches: {}
      labels:
        entries:
        - env/staging
        - updatebot
      milestone: ""
      missingLabels:
        entries:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
      review_approved_required: false
  postsubmits:
  - name: release
    context: "release"
    source: "release.yaml"
    branches:
<<<<<<< HEAD
    - master
    - main
=======
    - ^main$
    - ^master$
>>>>>>> update .lighthouse (https://github.com/jenkins-x/jx3-pipeline-catalog) from master (4a22dee8a67f66e5012729808de081d2f4d0e715) to master (7ee24d404e627df93044dba4ff842398928892d7)
