# Source: zeebe-operate-helm/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2020-12-01T13:05:05Z"
  deletionTimestamp: null
  name: 'zeebe-operate-helm-0.0.36'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        accountReference:
          - id: jenkins-x-bot
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: salaboy
      branch: master
      committer:
        accountReference:
          - id: jenkins-x-bot
            provider: jenkins.io/git-github-userid
        email: jenkins-x@googlegroups.com
        name: salaboy
      message: |
        chore: added variables
      sha: c228ad0a21d111d2d7b0f0b0c80a44d6100d34c2
    - author:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: salaboy@gmail.com
        name: salaboy
      branch: master
      committer:
        accountReference:
          - id: salaboy-2
            provider: jenkins.io/git-github-userid
        email: salaboy@gmail.com
        name: salaboy
      message: |
        replacing repo and tag only at the beggining of a new line
      sha: 2b02df931513e8a0164045f94c98eaa1e36e9924
  gitCloneUrl: https://github.com/zeebe-io/zeebe-operate-helm.git
  gitHttpUrl: https://github.com/zeebe-io/zeebe-operate-helm
  gitOwner: zeebe-io
  gitRepository: zeebe-operate-helm
  name: 'zeebe-operate-helm'
  releaseNotesURL: https://github.com/zeebe-io/zeebe-operate-helm/releases/tag/v0.0.36
  version: v0.0.36
status: {}
